export const LOAD_CONFIG = 'LOAD_CONFIG';

export const LOAD_LANGUAGES = 'LOAD_LANGUAGES';
export const SET_LANGUAGES = 'SET_LANGUAGES';
export const SELECT_LANGUAGE = 'SELECT_LANGUAGE';
export const SET_SELECTED_LANGUAGE = 'SET_SELECTED_LANGUAGE';

export const LOAD_DICTIONARY = 'LOAD_DICTIONARY';
export const SET_DICTIONARY = 'SET_DICTIONARY';
export const REMOVE_DICTIONARY = 'REMOVE_DICTIONARY';
export const LOAD_PARTS_OF_SPEECHES = 'LOAD_PARTS_OF_SPEECHES';
export const STORE_PARTS_OF_SPEECHES = 'STORE_PARTS_OF_SPEECHES';

export const SELECT_WORD = 'SELECT_WORD';
export const SET_EDIT_MODE = 'SET_EDIT_MODE';

export const EDIT_WORD_NAME = 'EDIT_WORD_NAME';
export const SET_WORD_NAME = 'SET_WORD_NAME';

export const CREATE_TRANSCRIPTION = 'CREATE_TRANSCRIPTION';
export const ADD_TRANSCRIPTION = 'ADD_TRANSCRIPTION';
export const DELETE_TRANSCRIPTION = 'DELETE_TRANSCRIPTION';
export const EDIT_TRANSCRIPTION = 'EDIT_TRANSCRIPTION';
export const SET_TRANSCRIPTION = 'SET_TRANSCRIPTION';

export const CREATE_SEMANTIC_BLOCK = 'CREATE_SEMANTIC_BLOCK';
export const ADD_SEMANTIC_BLOCK = 'ADD_SEMANTIC_BLOCK';
export const REMOVE_SEMANTIC_BLOCK_AND_SAVE_DICTIONARY = 'REMOVE_SEMANTIC_BLOCK_AND_SAVE_DICTIONARY';
export const DELETE_SEMANTIC_BLOCK = 'DELETE_SEMANTIC_BLOCK';

export const ADD_PART_OF_SPEECH = 'ADD_PART_OF_SPEECH';
export const SET_PART_OF_SPEECH = 'SET_PART_OF_SPEECH';
export const REMOVE_PART_OF_SPEECH_AND_SAVE_DICTIONARY = 'REMOVE_PART_OF_SPEECH_AND_SAVE_DICTIONARY';
export const DELETE_PART_OF_SPEECH = 'DELETE_PART_OF_SPEECH';

export const ADD_MEANING = 'ADD_MEANING';
export const CREATE_MEANING = 'CREATE_MEANING';

export const EDIT_MEANING_REMARK = 'EDIT_MEANING_REMARK';
export const SET_MEANING_REMARK = 'SET_MEANING_REMARK';
export const DELETE_MEANING_REMARK = "DELETE_MEANING_REMARK";

export const EDIT_TRANSLATION = 'EDIT_TRANSLATION';
export const SET_TRANSLATION = 'SET_TRANSLATION';
export const DELETE_TRANSLATION = 'DELETE_TRANSLATION';

export const EDIT_ELABORATION = 'EDIT_ELABORATION';
export const SET_ELABORATION = 'SET_ELABORATION';
export const DELETE_ELABORATION = 'DELETE_ELABORATION';

export const EDIT_EXAMPLE_REMARK = 'EDIT_EXAMPLE_REMARK';
export const SET_EXAMPLE_REMARK = 'SET_EXAMPLE_REMARK';
export const DELETE_EXAMPLE_REMARK = 'DELETE_EXAMPLE_REMARK';

export const EDIT_EXAMPLE_EXPRESSION = 'EDIT_EXAMPLE_EXPRESSION';
export const SET_EXAMPLE_EXPRESSION = 'SET_EXAMPLE_EXPRESSION';
export const DELETE_EXAMPLE_EXPRESSION = 'DELETE_EXAMPLE_EXPRESSION';

export const EDIT_EXAMPLE_EXPLANATION = 'EDIT_EXAMPLE_EXPLANATION';
export const SET_EXAMPLE_EXPLANATION = 'SET_EXAMPLE_EXPLANATION';
export const DELETE_EXAMPLE_EXPLANATION = 'DELETE_EXAMPLE_EXPLANATION';

export const DELETE_EXAMPLE = 'DELETE_EXAMPLE';
