export const LOAD_LANGUAGES = 'LOAD_LANGUAGES';
export const SET_LANGUAGES = 'SET_LANGUAGES';
export const SELECT_LANGUAGE = 'SELECT_LANGUAGE';

export const LOAD_DICTIONARY = 'LOAD_DICTIONARY';
export const SET_DICTIONARY = 'SET_DICTIONARY';
export const REMOVE_DICTIONARY = 'REMOVE_DICTIONARY';

export const SELECT_WORD = 'SELECT_WORD';